sequenceDiagram
    actor user as User
    box Purple SDK
        participant sdk as SDK
    end
    box Grey CryptPay
        participant vvs_svc as Viviswap-Service
    end
    box Blue External
        participant vvs_api as Viviswap-API
    end
    user->>+sdk: set_viviswap_kyc_document()
    sdk->>+vvs_svc: set_kyc_details(KycData::Document)
    vvs_svc->>+vvs_api: set_kyc_step_document