sequenceDiagram
    actor user as User
    box Purple SDK
        participant sdk as SDK
    end
    box Grey CryptPay
        participant vvs_svc as Viviswap-Service
    end
    box Blue External
        participant vvs_api as Viviswap-API
    end
    user->>+sdk: start_kyc_verification_for_viviswap()
    sdk->>+vvs_svc: add_user)=
    vvs_svc->>+vvs_api: create_user
    vvs_api-->>-vvs_svc: ViviswapApiUser
    vvs_svc-->>-sdk: NewUser
    sdk-->>-user: NewViviswapUser