sequenceDiagram
    actor user as User
    box Purple SDK
        participant sdk as SDK
    end
    box Grey CryptPay
        participant req as Requests-Aggregator
        participant vvs_service as Viviswap-Service
    end
    box Blue External
        participant vvs_api as Viviswap-API
    end
    user->>+sdk: update_iban_for_viviswap()
    sdk-->>sdk: sdk.verify_pin()
    sdk-->>sdk: sdk.ensure_detail()
    sdk-->>-user: Address Detail