# @file Makefile
# @author Team Lobster 🦞
# @copyright ETO GRUPPE TECHNOLOGIES GmbH

.PHONY = build run

build:
	swift build

run: 
	$(MAKE) build
	chmod +x run_all_examples.sh && ./run_all_examples.sh