site_name: ETOPay Docs
not_in_nav: |
  javadoc
  rust-docs
plugins:
  - privacy:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/privacy
      assets: true
      assets_fetch: true
      assets_fetch_dir: assets/external
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - typedoc:
      source: "../bindings/wasm/pkg/etopay_sdk_wasm.d.ts"
      output_dir: "jstsdocs"
      tsconfig: "../bindings/wasm/tsconfig.json"
      options: "../bindings/wasm/typedoc.json"
      name: "ETOPay Docs"
      title_link: "/SDK%20Reference/SDK%20API%20Reference/"
  - mike

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      title: On this page
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "../"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
extra_css:
  - stylesheets/extra.css
theme:
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.prune
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.footnote.tooltips
    - search.suggest
    - search.highlight
    - search.share
  name: material
  font:
    text: Exo 2
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: custom
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode

copyright: Copyright &copy; 2025 - ETOSPHERES Labs GmbH <br/> <a href="#__consent">Change cookie settings</a>
extra:
  analytics:
    provider: custom
    site_id: 2
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@etospheres.com
      name: Contact Us
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ETOSPHERES
      name: X
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/etospheres/
      name: LinkedIn
    - icon: fontawesome/brands/discord
      link: https://discord.gg/QSb2EG8EFX
      name: ETOPay Discord channel
  version:
    provider: mike
    default: latest
  consent:
    cookies:
      analytics:
        name: Analytics
        checked: true
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

extra_javascript:
  - javascripts/consent.js
