name: deploy-wasm

# Only manual for now since there are no snapshot releases
on:
  workflow_dispatch:

jobs:
  publish-sdk-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "21.12"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: 'pnpm'

      - name: Set up .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build wasm sdk
        run: |
          cd sdk/bindings/wasm
          wasm-pack build --release --scope etopay --target nodejs --out-dir out/web/pkg

      - name: Publish to npm
        run: |
          cd sdk/bindings/wasm
          wasm-pack publish out/web --access public

      - name: Pack artifact
        run: |
          cd sdk/bindings/wasm
          wasm-pack pack out/web

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: etopay-sdk-wasm
          path: sdk/bindings/wasm/out/**/*.tgz
          if-no-files-found: error
          retention-days: 7
          overwrite: true
